psql -p $METHINKS_DB_PORT -c "CREATE DATABASE $METHINKS_DB_NAME"
# Create methinks user
psql -p $METHINKS_DB_PORT -c "CREATE ROLE $METHINKS_DB_USER WITH PASSWORD '$METHINKS_DB_PASSWD';"
# Give privileges
psql -p $METHINKS_DB_PORT -c "GRANT ALL PRIVILEGES ON DATABASE $METHINKS_DB_NAME to $METHINKS_DB_USER;"
